[build]
  functions = "functions"  # La carpeta que contiene tus funciones Netlify

[[redirects]]
  from = "/user/*"
  to = "/.netlify/functions/user/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[build.environment]
  NODE_VERSION = "18.16.0"
